# Generated by Django 3.2.8 on 2023-06-04 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0002_alter_taggeditem_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='taggeditem',
            managers=[
            ],
        ),
    ]
